name: Check Signed PR
on:
  pull_request:
    branches:
      - 'dev'
  push:
    branches:
      - 'dev'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:
    name: Check Signed Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check signed commits in PR
        uses: 1Password/check-signed-commits-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}