name: Check conflict branch in PR 
on:
  schedule:
    - cron: '*/2 * * * *' # Run at every 2 minutes
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check conflict branch in PR
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check conflict branch in PR
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: conflict
