name: Check conflict branch in PR 
on:
  schedule:
    - cron: '*/5 * * * *' # Run at every 5 minutes

jobs:
  build:
    name: Check conflict branch in PR
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check conflict branch in PR
        uses: ./